version: "3.7"

services:
  locadora:
    image: mehiell/locadora
    build:
      context: .
      dockerfile: src/Locadora.WebApi/Dockerfile
    container_name: locadora
    environment:
      - ASPNETCORE_URLS=http://+
    ports:
      - "80:80"   
