version: "3.7"

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: locadora-sql-server
    restart: always 
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=L@c@d@r@123
      - MSSQL_PID=Express
    ports:
      - "1433:1433" 
  locadora:
    image: mehiell/locadora:latest
    container_name: locadora
    restart: always 
    environment:
      - ASPNETCORE_URLS=http://+
      - AppSettings__ConnectionString=Data Source=host.docker.internal;Initial Catalog=LocadoraDbContext;User ID=sa;Password=L@c@d@r@123;MultipleActiveResultSets=true
    ports:
      - "80:80"
    depends_on:
      - sql-server
