# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      locadora-api: ./backend/src/Locadora.WebApi

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image docker
        run: docker build -t locadora .
        working-directory: ${{env.locadora-api}}
      - name: Tags image docker
        run: |
          docker tag locadora ${{ secrets.DOCKER_USER }}/locadora:${{ github.sha }}
          docker tag locadora ${{ secrets.DOCKER_USER }}/locadora:latest
      - name: Push image docker
        run: |
          docker push ${{ secrets.DOCKER_USER }}/locadora:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/locadora:latest
